---
title: NHS Levels of RAP
format:
  html:
    css: frameworks_style.css
    page-layout: full
date: "2025-10-23T14:21:39+01:00"
---

<!-- Hide as no python-content or r-content blocks -->
<style>
      #quarto-announcement {
        display: none !important;
      }
</style>

The following framework is from the NHS RAP Community of Practice: **[NHS RAP Levels of RAP Framework](https://nhsdigital.github.io/rap-community-of-practice/introduction_to_RAP/levels_of_RAP/)**.

It is © 2024 Crown Copyright (NHS England), shared under the terms of the [Open Government 3.0 licence](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/).

The specific version of the framework copied below is that from commit [2549256](https://github.com/NHSDigital/rap-community-of-practice/commit/2549256498886d6d7ea4cdb736e2a2864c8bb461) (9th September 2024).

### 🥉 Baseline

RAP fundamentals offering resilience against future change.

| Criteria | Covered on page... |
| - | - |
| Data produced by code in an open-source language (e.g., Python, R). | <span class="section-link">[Open-source languages](foss.qmd)</span> |
| Code is version controlled (see [Git basics](https://nhsdigital.github.io/rap-community-of-practice/training_resources/git/introduction-to-git/) and [using Git collaboratively](https://nhsdigital.github.io/rap-community-of-practice/training_resources/git/using-git-collaboratively/) guides). | <span class="section-link">[Version control](../setup/version.qmd)</span> |
| Repository includes a README.md file (or equivalent) that clearly details steps a user must follow to reproduce the code (use [NHS Open Source Policy section on Readmes](https://github.com/nhsx/open-source-policy/blob/main/open-source-policy.md#b-readmes) as a guide). | <span class="section-link">[Documentation](../style_docs/documentation.qmd)</span> |
| Code has been [peer reviewed](https://nhsdigital.github.io/rap-community-of-practice/implementing_RAP/workflow/code-review/). | <span class="section-link">[Peer review](../sharing/peer_review.qmd)</span> |
| Code is [published in the open](https://nhsdigital.github.io/rap-community-of-practice/implementing_RAP/publishing_code/how-to-publish-your-code-in-the-open/) and linked to & from accompanying publication (if relevant). | <span class="section-link">[Sharing and archiving](../sharing/archive.qmd)</span> |
: {tbl-colwidths="[60,40]"}

### 🥈 Silver

Implementing best practice by following good analytical and software engineering standards.

Meeting all of the above requirements, plus:

| Criteria | Covered on page... |
| - | - |
| Outputs are produced by code with minimal manual intervention. | <span class="section-link">[Full run](../experiments/full_run.qmd)</span> |
| Code is well-documented including user guidance, explanation of code structure & methodology and [docstrings](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/python-functions/#documentation) for functions. | <span class="section-link">[Documentation](../style_docs/documentation.qmd)</span> <span class="section-link">[Docstrings](../style_docs/docstrings.qmd)</span> |
| Code is well-organised following [standard directory format](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/project-structure-and-packaging/). | <span class="section-link">[Structuring as a package](../setup/package.qmd)</span> |
| [Reusable functions](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/python-functions/) and/or classes are used where appropriate. | <span class="section-link">[Code organisation](../setup/code_structure.qmd)</span> |
| Code adheres to agreed coding standards (e.g PEP8, [style guide for Pyspark](https://nhsdigital.github.io/rap-community-of-practice/training_resources/pyspark/pyspark-style-guide/)). | <span class="section-link">[Linting](../style_docs/linting.qmd)</span> |
| Pipeline includes a testing framework ([unit tests](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/unit-testing/), [back tests](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/backtesting/)). | <span class="section-link">[Tests](../verification_validation/tests.qmd)</span> |
| Repository includes dependency information (e.g. [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files), [PipFile](https://github.com/pypa/pipfile/blob/main/README.rst), [environment.yml](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/virtual-environments/conda/)). | <span class="section-link">[Environments](../setup/environment.qmd)</span> |
| [Logs](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/logging-and-error-handling/) are automatically recorded by the pipeline to ensure outputs are as expected. | <span class="section-link">[Logging](../model/logs.qmd)</span> |
| Data is handled and output in a [Tidy data format](https://medium.com/@kimrodrikwa/untidy-data-a90b6e3ebe4c). | <span class="section-link">[Parameters from file](../inputs/parameters_file.qmd)</span> <span class="section-link">[Performance measures](../output_analysis/outputs.qmd)</span> |
: {tbl-colwidths="[60,40]"}

### 🥇 Gold 

Analysis as a product to further elevate your analytical work and enhance its reusability to the public.

Meeting all of the above requirements, plus:

| Criteria | Covered on page... |
| - | - |
| Code is fully [packaged](https://packaging.python.org/en/latest/). | <span class="section-link">[Structuring as a package](../setup/package.qmd)</span> |
| Repository automatically runs tests etc. via CI/CD or a different integration/deployment tool e.g. [GitHub Actions](https://docs.github.com/en/actions). | <span class="section-link">[GitHub actions](../style_docs/github_actions.qmd)</span> |
| Process runs based on event-based triggers (e.g., new data in database) or on a schedule. | N/A |
| Changes to the RAP are clearly signposted. E.g. a changelog in the package, releases etc. (See gov.uk info on [Semantic Versioning](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/versioning.md)). | <span class="section-link">[Changelog](../sharing/changelog.qmd)</span> |
: {tbl-colwidths="[60,40]"}

<br><br>
