---
title: STARS reproducibility recommendations
format:
  html:
    css: frameworks_style.css
    page-layout: full
date: "2025-10-23T14:21:39+01:00"
---

<!-- Hide as no python-content or r-content blocks -->
<style>
      #quarto-announcement {
        display: none !important;
      }
</style>

As part of the [STARS project](https://pythonhealthdatascience.github.io/stars/), a series of computational reproducibility assessments were conducted. From these, several recommendations were shared to support reproducibility of healthcare discrete-event simulation (DES) models, as described in:

> Heather, A. Monks, T. Harper, A. Mustafee, N. Mayne, A. **On the reproducibility of discrete-event simulation studies in health research: an empirical study using open models** (2025). Journal of Simulation. <https://doi.org/10.1080/17477778.2025.2552177>.

Those marked with a star (⭐) were identified as having the greatest impact in Heather et al. 2025.

### Recommendations to support reproduction

::: {.grey-table}

| Recommendation | Covered on page... |
| - | - |
| **Set-up** | 
| Share code with an open licence ⭐  | <span class="section-link">[Licensing](/pages/guide/sharing/licence.qmd)</span> |
| Link publication to a specific version of the code | <span class="section-link">[Changelog](/pages/guide/sharing/changelog.qmd)</span> |
| List dependencies and versions | <span class="section-link">[Environments](/pages/guide/setup/environment.qmd)</span> |
| **Running the model** |
| Provide code for all scenarios and sensitivity analyses ⭐ | <span class="section-link">[Scenario and sensitivity analysis](/pages/guide/experiments/scenarios.qmd)</span> |
| Ensure model parameters are correct ⭐ | <span class="section-link">[Full run](/pages/guide/experiments/full_run.qmd)</span> |
| Control randomness | <span class="section-link">[Randomness](/pages/guide/model/distributions.qmd)</span> |
| **Outputs** |
| Include code to calculate all required model outputs ⭐ | <span class="section-link">[Performance measures](/pages/guide/output_analysis/outputs.qmd)</span> |
| Include code to generate the tables, figures, and other reported results ⭐ | <span class="section-link">[Producing tables and figures](/pages/guide/experiments/tables_figures.qmd)</span> |
: {tbl-colwidths="[60,40]"}

:::

### Recommendations to support troubleshooting and reuse

::: {.grey-table}

| Recommendation | Covered on page... |
| - | - |
| **Design** |
| Separate model code from applications | Not covered as we don't create apps in this book, but simply: keep model code separate from app code. As an example, in previous work we made a simulation as a package ([treat-sim](https://github.com/pythonhealthdatascience/stars-treat-sim)) hosted on PyPI, then imported that to the [streamlit web app](https://github.com/pythonhealthdatascience/stars-streamlit-example/tree/main) |
| Avoid hard-coded parameters | <span class="section-link">[Parameters from script](/pages/guide/inputs/parameters_script.qmd)</span> <span class="section-link">[Parameters from file](/pages/guide/inputs/parameters_file.qmd)</span> |
| Minimise code duplication | <span class="section-link">[Code organisation](/pages/guide/setup/code_structure.qmd)</span> |
| **Clarity** |
| Comment sufficiently | <span class="section-link">[Docstrings](/pages/guide/style_docs/docstrings.qmd)</span> |
| Ensure clarity and consistency in the model results tables | <span class="section-link">[Performance measures](/pages/guide/output_analysis/outputs.qmd)</span> |
| Include run instructions | <span class="section-link">[Documentation](/pages/guide/style_docs/documentation.qmd)</span> |
| State run times and machine specifications | <span class="section-link">[Documentation](/pages/guide/style_docs/documentation.qmd)</span> |
| **Functionality** |
| Optimise model run time | <span class="section-link">[Parallel processing](/pages/guide/output_analysis/parallel.qmd)</span> |
| Save outputs to a file | <span class="section-link">[Scenario and sensitivity analysis](/pages/guide/experiments/scenarios.qmd)</span> <span class="section-link">[Producing tables and figures](/pages/guide/experiments/tables_figures.qmd)</span> |
| Avoid excessive output files | <span class="section-link">[Scenario and sensitivity analysis](/pages/guide/experiments/scenarios.qmd)</span> |
| Address large file sizes | <span class="section-link">[Scenario and sensitivity analysis](/pages/guide/experiments/scenarios.qmd)</span> |
: {tbl-colwidths="[40,60]"}

:::
