repos:
  - repo: local
    hooks:
      - id: quarto-r-include-check
        name: Block R Quarto file includes which break lintr
        entry: .pre-commit-hooks/check-no-quarto-r-include.sh
        language: script
        files: \.qmd$
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3
    hooks:
      - id: lintr
        args: [--warn_only]
        verbose: true