project:
  type: book
  preview:
    browser: true

book:
  title: "Reproducible Discrete-Event Simulation in Python and R "
  chapters:
  - index.qmd
  favicon: images/stars_logo_blue.png
  search:
    location: navbar
    type: overlay
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars_wp1_summary
  sidebar:
    logo: images/stars_logo_blue.png

format:
  html:
    theme: cosmo
    toc: true