project:
  type: website
  preview:
    browser: true
  render:
    - "*.qmd"
    - "pages/**/*.qmd"
    - "!_*.md"
    - "!examples/"

website:
  title: "DES RAP"
  site-url: "https://pythonhealthdatascience.github.io/des_rap_book/"
  google-analytics: "G-W2FC4GDHFK"
  cookie-consent: true
  page-navigation: true
  search: false
  favicon: images/stars_logo_blue.png
  navbar:
    logo: images/stars_logo_white.png
    collapse-below: "sm"
    left:
      - text: Step-by-step guide
        href: pages/guide/introduction.qmd
      - text: Examples
        href: pages/example_models/example_models.qmd
      - text: Frameworks
        menu:
          - pages/frameworks/levels_of_rap.qmd
          - pages/frameworks/stars_reproducibility.qmd
      - text: Intros
        menu:
          - text: Intro to DES
            href: pages/intros/des.qmd
          - text: Intro to reproducibility and RAPs
            href: pages/intros/rap.qmd
          - text: Intro to FOSS
            href: pages/intros/foss.qmd
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/des_rap_book
  announcement:
    dismissable: false
    content: |
      <div class="language-selector">
        Choose your language:&nbsp;&nbsp;
        <button class="language-button" onclick="setLanguage('python')">Python</button>
        <button class="language-button" onclick="setLanguage('r')">R</button>
      </div>
    position: below-navbar
  sidebar:
    - id: learn
      title: "Learn"
      style: "docked"
      contents:
        - text: Introduction
          href: pages/guide/introduction.qmd
        - section: "Setup"
          contents:
          - pages/guide/setup/version.qmd
          - pages/guide/setup/environment.qmd
          - pages/guide/setup/package.qmd
          - pages/guide/setup/code_structure.qmd
        - section: "Model inputs"
          contents:
          - pages/guide/inputs/input_modelling.qmd
          - pages/guide/inputs/input_data.qmd
          - pages/guide/inputs/parameters_script.qmd
          - pages/guide/inputs/parameters_file.qmd
          - pages/guide/inputs/parameters_validation.qmd
        - section: "Model building"
          contents:
          - pages/guide/model/distributions.qmd
          - pages/guide/model/patients.qmd
          - pages/guide/model/process.qmd
          - pages/guide/model/logs.qmd
        - section: "Output analysis"
          contents:
          - pages/guide/output_analysis/warmup.qmd
          - pages/guide/output_analysis/outputs.qmd
          - pages/guide/output_analysis/replications.qmd
          - pages/guide/output_analysis/length_warmup.qmd
          - pages/guide/output_analysis/n_reps.qmd
          - pages/guide/output_analysis/parallel.qmd
        - section: "Experimentation"
          contents:
          - pages/guide/experiments/scenarios.qmd
          - pages/guide/experiments/tables_figures.qmd
          - pages/guide/experiments/full_run.qmd
        - section: "Verification & validation"
          contents:
          - pages/guide/verification_validation/verification_validation.qmd
          - pages/guide/verification_validation/tests.qmd
          - pages/guide/verification_validation/mathematical.qmd
          - pages/guide/verification_validation/quality_assurance.qmd
        - section: "Style & documentation"
          contents:
          - pages/guide/style_docs/linting.qmd
          - pages/guide/style_docs/docstrings.qmd
          - pages/guide/style_docs/github_actions.qmd
          - pages/guide/style_docs/documentation.qmd
        - section: "Collaboration & sharing"
          contents:
          - pages/guide/sharing/peer_review.qmd
          - pages/guide/sharing/licence.qmd
          - pages/guide/sharing/citation.qmd
          - pages/guide/sharing/changelog.qmd
          - pages/guide/sharing/archive.qmd
        - section: "Closing remarks"
          contents:
          - pages/guide/further_info/conclusion.qmd
          - pages/guide/further_info/feedback.qmd

  page-footer:
    left:
      - text: |
           The STARS project is supported by the Medical Research Council [grant number MR/Z503915/1].
    center:
      - text: |
          Part of the STARS research project.<br>
          Code licence: <a href="https://opensource.org/license/mit" target="_blank" rel="noopener">MIT</a>.  
          Text licence: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC-BY-SA 4.0</a>.
    right:
      - text: |
          Heather, A., Monks, T., Mustafee, N., & Harper, A. (2025). DES RAP Book: Reproducible Discrete-Event Simulation in Python and R. https://github.com/pythonhealthdatascience/des_rap_book. https://doi.org/10.5281/zenodo.17094155.

format:
  html:
    theme:
      - cosmo
    toc: true
    toc-depth: 2
    number-sections: false
    crossrefs-hover: false
    lightbox: true
    title-block-banner: images/banner.png
    title-block-banner-color: "#ffffff"
    css:
      - styles/headings.css
      - styles/general.css
      - styles/buttons.css
      - styles/language-selector.css
      - styles/callout.css
      - styles/tables.css
      - styles/webex.css
    include-after-body:
      - scripts/webex.js
      - scripts/language-selector.js

params:
  language: "python"  # Default language parameter