project:
  type: book
  preview:
    browser: true

book:
  title: "Reproducible Discrete-Event Simulation in Python and R"
  chapters:
  - index.qmd
  - part: "Introduction"
    chapters:
    - pages/intro/rap.qmd
    - pages/intro/guidelines.qmd
    - pages/intro/foss.qmd
    - pages/intro/examples.qmd
  - part: "Setup"
    chapters:
    - pages/setup/version.qmd
    - pages/setup/environment.qmd
    - pages/setup/package.qmd
    - pages/setup/code_structure.qmd
  - part: "Model inputs"
    chapters:
    - pages/inputs/input_modelling.qmd
    - pages/inputs/input_data.qmd
    - pages/inputs/parameters_script.qmd
    - pages/inputs/parameters_file.qmd
    - pages/inputs/parameters_validation.qmd
  - part: "Model building"
    chapters:
    - pages/model/distributions.qmd
    - pages/model/patients.qmd
    - pages/model/process.qmd
  - part: "Output analysis"
    chapters:
    - pages/output_analysis/outputs.qmd
    - pages/output_analysis/warmup.qmd
    - pages/output_analysis/replications.qmd
    - pages/output_analysis/n_reps.qmd
    - pages/output_analysis/parallel.qmd
  - part: "Experimentation"
    chapters:
    - pages/experiments/scenarios.qmd
    - pages/experiments/sensitivity.qmd
  - part: "Verification & validation"
    chapters:
    - pages/verification_validation/logs.qmd
    - pages/verification_validation/tests.qmd
    - pages/verification_validation/validation.qmd
  - part: "Style & documentation"
    chapters:
    - pages/style_docs/linting.qmd
    - pages/style_docs/docstrings.qmd
    - pages/style_docs/documentation.qmd
    - pages/style_docs/github_actions.qmd
  - part: "Reports & manuscripts"
    chapters:
    - pages/reports/tables_figures.qmd
    - pages/reports/full_run.qmd
  - part: "Collaboration & sharing"
    chapters:
    - pages/sharing/peer_review.qmd
    - pages/sharing/licence.qmd
    - pages/sharing/archive.qmd
    - pages/sharing/citation.qmd
    - pages/sharing/changelog.qmd
  - part: "Further information"
    chapters:
    - pages/further_info/acknowledgements.qmd
  favicon: images/stars_logo_blue.png
  search:
    location: navbar
    type: overlay
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/des_rap_book
  sidebar:
    logo: images/stars_logo_blue.png

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    crossrefs-hover: false
    css:
      - styles/general.css
      - styles/language-selector.css
      - styles/callout.css
    filters:
      - filters/guidelines-filter.lua
    include-after-body:
        text: |
            <script type="application/javascript" src="../../scripts/language-selector.js"></script>

params:
  language: "python"  # Default language parameter