project:
  type: book
  preview:
    browser: true

book:
  title: "Reproducible Discrete-Event Simulation in Python and R "
  chapters:
  - index.qmd
  - part: "Introduction"
    chapters:
    - pages/intro/rap.qmd
    - pages/intro/guidelines.qmd
    - pages/intro/foss.qmd
  - part: "Setup"
    chapters:
    - pages/setup/version.qmd
    - pages/setup/environment.qmd
    - pages/setup/package.qmd
    - pages/setup/code_structure.qmd
  - part: "Model creation"
    chapters:
    - pages/model/parameters.qmd
    - pages/model/distributions.qmd
    - pages/model/patients.qmd
    - pages/model/process.qmd
    - pages/model/logs.qmd
  - part: "Model execution"
    chapters:
    - pages/execution/outputs.qmd
    - pages/execution/warmup.qmd
    - pages/execution/replications.qmd
    - pages/execution/parallel.qmd
  - part: "Analysis"
    chapters:
    - pages/analysis/tables_figures.qmd
    - pages/analysis/scenarios.qmd
    - pages/analysis/full_run.qmd
  - part: "Quality assurance"
    chapters:
    - pages/quality/docstrings.qmd
    - pages/quality/linting.qmd
    - pages/quality/tests.qmd
    - pages/quality/github_actions.qmd
    - pages/quality/peer_review.qmd
  - part: "Sharing the model"
    chapters:
    - pages/sharing/documentation.qmd
    - pages/sharing/licence.qmd
    - pages/sharing/archive.qmd
    - pages/sharing/citation.qmd
    - pages/sharing/changelog.qmd
  favicon: images/stars_logo_blue.png
  search:
    location: navbar
    type: overlay
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars_wp1_summary
  sidebar:
    logo: images/stars_logo_blue.png

format:
  html:
    theme: cosmo
    toc: true