project:
  type: website
  preview:
    browser: true

website:
  title: "Reproducible Discrete-Event Simulation in Python and R"
  sidebar:
    style: "docked"
    logo: images/stars_logo_blue.png
    contents:
    - index.qmd
    - section: "Introduction"
      contents:
      - pages/intro/rap.qmd
      - pages/intro/guidelines.qmd
      - pages/intro/foss.qmd
      - pages/intro/examples.qmd
    - section: "Setup"
      contents:
      - pages/setup/version.qmd
      - pages/setup/environment.qmd
      - pages/setup/package.qmd
      - pages/setup/code_structure.qmd
    - section: "Model inputs"
      contents:
      - pages/inputs/input_modelling.qmd
      - pages/inputs/input_data.qmd
      - pages/inputs/parameters_script.qmd
      - pages/inputs/parameters_file.qmd
      - pages/inputs/parameters_validation.qmd
    - section: "Model building"
      contents:
      - pages/model/distributions.qmd
      - pages/model/patients.qmd
      - pages/model/process.qmd
    - section: "Output analysis"
      contents:
      - pages/output_analysis/outputs.qmd
      - pages/output_analysis/warmup.qmd
      - pages/output_analysis/replications.qmd
      - pages/output_analysis/n_reps.qmd
      - pages/output_analysis/parallel.qmd
    - section: "Experimentation"
      contents:
      - pages/experiments/scenarios.qmd
      - pages/experiments/sensitivity.qmd
    - section: "Verification & validation"
      contents:
      - pages/verification_validation/logs.qmd
      - pages/verification_validation/tests.qmd
      - pages/verification_validation/validation.qmd
    - section: "Style & documentation"
      contents:
      - pages/style_docs/linting.qmd
      - pages/style_docs/docstrings.qmd
      - pages/style_docs/documentation.qmd
      - pages/style_docs/github_actions.qmd
    - section: "Reports & manuscripts"
      contents:
      - pages/reports/tables_figures.qmd
      - pages/reports/full_run.qmd
    - section: "Collaboration & sharing"
      contents:
      - pages/sharing/peer_review.qmd
      - pages/sharing/licence.qmd
      - pages/sharing/archive.qmd
      - pages/sharing/citation.qmd
      - pages/sharing/changelog.qmd
    - section: "Further information"
      contents:
      - pages/further_info/acknowledgements.qmd
  favicon: images/stars_logo_blue.png
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/des_rap_book
  announcement:
    dismissable: false
    content: |
      <div class="language-selector">
        Choose your language:&nbsp;&nbsp;
        <button class="language-button" onclick="setLanguage('python')">Python</button>
        <button class="language-button" onclick="setLanguage('r')">R</button>
      </div>
    position: below-navbar

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    crossrefs-hover: false
    css:
      - styles/general.css
      - styles/language-selector.css
      - styles/callout.css
    filters:
      - filters/guidelines-filter.lua
    include-after-body:
        text: |
            <script type="application/javascript" src="../../scripts/language-selector.js"></script>

params:
  language: "python"  # Default language parameter