name: des-rap-book
channels:
  - conda-forge
dependencies:
  - jupyter=1.1.1
  - pandas=2.2.3
  - plotly=6.0.1
  - pylint=3.3.7
  - pytest=8.3.5
  - python=3.9.22
  - pip:
    - distfit==1.8.6
    - jupytext==1.17.1
