---
title: ❌ Sharing and archiving
---

::: {.pale-blue}

**Learning objectives:**

* TODO

**Relevant reproducibility guidelines:**

* NHS Levels of RAP (🥉): Code is published in the open and linked to & from accompanying publication (if relevant).

:::

## Sharing your simulation model

In our recent review, we explored whether and how healthcare discrete-event simulation (DES) models have been shared over the last few years:

> Monks, T., & Harper, A. (2023). **Computer model and code sharing practices in healthcare discrete-event simulation: a systematic scoping review**. Journal of Simulation, 19(1), 108–123. <https://doi.org/10.1080/17477778.2023.2260772>.

Here are some key take-homes from that study...

::: {.pale-green}

<div class="h3-tight"></div>

### 1. Share your model

:::

**Any sharing is better than nothing**.

Our review found only 8.3% (n=47/564) of healthcare DES studies shared their model.

You may consider including a data availability statement such as "the materials used within this study are available from the corresponding author on reasonable request". However, we do **not recommend** relying on this approach. Studies show these statements are rarely upheld, even if well intentioned to begin with - often because projects and staff move on, and code gets lost. For example, a large review by [Janssen et al. (2020)](https://doi.org/10.1016/j.envsoft.2020.104873) found that less than 1% of authors responded - and of those, fewer still shared code.

Instead, you should aim to share as much as possible directly - ideally, providing complete materials, from input data (see [Input data management](../inputs/input_data.qmd) page for details), through to the code needed to generate figures and tables.

::: {.pale-green}

<div class="h3-tight"></div>

### 2. Use effective sharing platforms

:::

**How you share matters.** Better platforms make it easier for others to access, review, and reuse your work.

Although it is possible to share code files as journal/report supplementary materials, we do **not recommend** this as a primary method. Supplementary files are often converted into awkward formats (such as PDF or Word), which strips away features like syntax highlighting and makes it difficult to run or modify the code. These files also lack support for collaborative tools like version control, issue tracking, and automated testing.

A better approach is to use dedicated code-sharing platforms like **GitHub** (the most popular for DES models in our review). These platforms are specifically designed for open sharing, allow version control, and make it easy for others to follow changes, contribute or raise issues.

For even better long-term access, deposit your code and materials in a **digital archive** (see the archiving section below for mode detail). This ensures your code is preserved and citable over time.

::: {.pale-green}

<div class="h3-tight"></div>

### 3. Don't leave sharing to the end of your project

:::

In our review, we found DES GitHub repositories with only one or a few commits, indicating that model code was uploaded only at the very end of the project. When sharing is left until the end, there's often less time to ensure quality: important elements like documentation, licenses, and usage instructions are frequently missing or rushed.

It's much better to plan for sharing from the outset - ideally by using version control from the start of your project. This makes it easier to keep track of changes, gradually improve documentation, and make sure everything is ready for when you're ready to publish.

::: {.pale-green}

<div class="h3-tight"></div>

### 4. Follow guidelines

:::

<!--
**Reporting guidelines** can help make sure ou document model clearly. Only 12.8% of the models in our review mentioned using a simulation eporting guideline or general checklist.

* STRESS-DES - replication
* ISPOR
* Zhang et al. - quality etc.

**Sharing guidelines** focus more on the code that is shared... how share... what have done..... etc.

* Stars frmaework - reuse
* STARS recommendations and NHS LEvels of RAP - as so central to this book - all about how model is structured when sharing...

WHAT DO THESE COME UNDER?

* TRACE (TRAnsparent and Comprehensive model Evaludation)
    * https://www.sciencedirect.com/science/article/pii/S1364815220309890?via%3Dihub - keeping notebooks can help...
-->

## Journal sharing requirements

<!--
if you are submitting publication about des, sharing requirements may be journal

Mandatory code sharing
Policies for mandatory code sharing
Badges awarded to articles with shared code

Review of shared artefacts
requiring certain things
e.g.Policies requiring details on the language and packages, commented code, and test data/problems sufficient for replication 
Policies requiring open licenses and clear documentation
Badges awarded following evaluation of artefacts (e.g., checking they are complete, executable and documented)
-->

## Archives

## How to archive your repository on Zenodo

<!--
we will go through example of zenodo... good for code...
-->

<br><br>
