---
title: ❌ Changelog
---

::: {.pale-blue}

**Learning objectives:**

* Understand **purpose** of a changelog.
* Learn **semantic versioning** conventions.
* Learn how to **write a changelog**.
* Learn how to create **GitHub releases**.

**Relevant reproducibility guidelines:**

* STARS Reproducibility Recommendations: Link publication to a specific version of the code.
* NHS Levels of RAP (🥇): Changes to the RAP are clearly signposted. E.g. a changelog in the package, releases etc.

:::

## 📝 What is a changelog?

A **changelog** is a document that records changes to a project over time. It's purpose is to make clear what has changed between versions of code and when those changes happened. They serve as an easier-to-read record of what's changed, than scrolling through commit logs!

::: {.python-content}

Changelogs are typically stored in a `CHANGELOG.md` file.

:::

::: {.r-content}

Changelogs are typically stored in a `CHANGELOG.md` file. For R packages, the convention is a `NEWS.md` file.

:::

Changelogs help make projects more **reproducible**. For example:

* When [sharing code for review](peer_review.qmd), a changelog makes it clear which version your reviewer should look at, and you can also show what changed before and after the review.

* When updating a report, or responding to feedback on a journal submission, you can link each manuscript to a specific version of the code. This ensures a clear record of what was changed after feedback (e.g., between a pre-print and accepted publication).

* When someone tries to reproduce your results, they can run the exact version of your code that you used, even if the project has moved on. The latest commit might not match your work anymore.

When working with software as an installed package, users will typically refer to the installed version number to know which features and changes are available.

## 🔢 Versioning

Projects use **semantic versioning** to structure version numbers. The rules are defined at <https://semver.org/>:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> 1. MAJOR version when you make incompatible API changes
> 2. MINOR version when you add functionality in a backward compatible manner
> 3. PATCH version when you make backward compatible bug fixes

*Semantic Versioning 2.0.0. <https://semver.org/>. CC BY 3.0.*

Projects commonly start at version `0.1.0`, with `0.y.z` versions considered "unstable". The SemVer guidance suggests incrementing the **minor** version as development progresses (i.e., `0.2.0`, `0.3.0`), and moving to major version changes when...TODO.

::: {.r-content}

For R packages, development versions often begin at `0.0.0.9000`. When ready for the first release, they increment to `0.1.0`. Some developers skip the `.9000` approach though and begin directly at `0.1.0`.

:::

Although semantic versioning has it's roots in software development, it's still equally valuable in research projects and analytic pipelines, like simulation development.

## 📑 Structuring a changelog

The most widely used convention is [Keep a Changelog](https://keepachangelog.com/en/1.1.0/). Their approach involves:

* A heading with the **version number** and **date**.
* Short **summary** sentence/s for the version.
* Bullet points organised under the following sub-headings:

> * `Added` for new features.
> * `Changed` for changes in existing functionality.
> * `Deprecated` for soon-to-be removed features.
> * `Removed` for now removed features.
> * `Fixed` for any bug fixes.
> * `Security` in case of vulnerabilities.
>
> *<https://keepachangelog.com/en/1.1.0/>. MIT licence. Olivier Lacan.*

Example:

```{.markdown}
TODO
```

