---
title: Containers, web execution and cloud IDEs
---

::: {.python-content}
For others to run the code you share, they will typically need to recreate your development environment. If you have used a [dependency management tool like conda](../setup/environment.qmd), they can use the configuration files you share (e.g. `environment.yaml`) to achieve this.

However, even with dependency management tools, setting up environments can still be time-consuming and error-prone. This is especially true for users who have not used the language before, may not have Python installed, or may not have a platform to work with it (an IDE).
:::

::: {.r-content}
For others to run the code you share, they will typically need to recreate your development environment. If you have used a [dependency management tool like renv](../setup/environment.qmd), they can use the configuration files you share (e.g. `DESCRIPTION`, `renv.lock`) to achieve this.

However, even with dependency management tools, setting up environments can still be time-consuming and error-prone. This is especially true for users who have not used the language before, may not have R installed, or may not have a platform to work with it (an integrated development environment - IDE).
:::

Solutions like containers and browser-based development environments can help eliminate these barriers, making it easier and faster for others to access and run your code.

<br>

## Containers

<!--TODO:
Explain what they are
Source file
What builds it
Types of container
What/How run it
Uses of them - e.g. from my experience - run the code in consistent place formally but not day-to-day... use to run day-to-day in my github action though...
--->

<br>

## Web-based code execution

<br>

## Cloud IDEs