---
title: "Impact"
---

<!-- Hide as no python-content or r-content blocks -->
<style>
      #quarto-announcement {
        display: none !important;
      }
</style>

This page highlights how the DES RAP Book is being used and referenced by the community. Let us know if you use the DES RAP Book, as we'd love to include it here!

## Research

* **Renal capacity model**  
  Model developed by [YiWen Hon](https://github.com/yiwen-h) and [Lucy Morgan](https://github.com/morganle-48) at the Strategy Unit, in collaboration with the Midlands Renal Operational Delivery Network (MRODN). Use SimPy to model Kidney Replacement Therapy (KRT) patient pathways for capacity planning. [Check out their model on GitHub](https://github.com/The-Strategy-Unit/renal-capacity-model/), also [archived on Zenodo](https://zenodo.org/doi/10.5281/zenodo.18599117), and read more about the project [in this article](https://www.strategyunitwm.nhs.uk/news/planning-rising-renal-demand-simulating-capacity-across-care-system).

> "The DES RAP Book was a valuable resource in our transition to open-source DES modelling. It provided us with a step-by-step structure to follow and guidance on best practice for writing code, tests and documentation for our package. Our model is being using in the Midlands, and beyond, for understanding future demand and capacity within Kidney Replacement Therapy." - **Lucy Morgan, Analytics Manager at The Strategy Unit**.

* **NHS model reuse project**  
  Collaboration between King’s, The Strategy Unit and the University of Exeter, where DES models are provided to NHS analysts. It explores whether they are able to reproduce and reuse them in their own context, and the model sample consists of our [python stroke example model](https://github.com/pythonhealthdatascience/pydesrap_stroke) and [R stroke example model](https://github.com/pythonhealthdatascience/rdesrap_stroke).

* **Stroke model of Same Day Emergency Care (SDEC) and CT Perfusion (CTP) scanning**  
  Hyperacute and acute stroke pathway model created by John Williams at Maidstone and Tunbridge Wells NHS Trust. Now being updated using DES RAP principles to add documentation, reproducible workflows, testing and other RAP infrastructure - [see updated model GitHub](https://github.com/Bergam0t/jw_hsma_des_stroke_project).

## Teaching and training use

The DES RAP Book is already being used and adapted in several teaching and training contexts.

* **HSMA "Little Book of DES"**  
  DES RAP Book is referenced in several places in the [Little Book of DES](https://des.hsma.co.uk/) from the [Health Service Modelling Associates (HSMA) Programme](https://hsma.co.uk/) at the University of Exeter, and is being used to support their curriculum revamp.

> "The DES RAP Book is a phenomenal resource that is being used extensively to enhance the training content of the national Health Service Modelling Associates (HSMA) Programme.  It provides clear, well-structured instructions and easy to follow examples that will ensure the approaches we teach to the next generation of health data scientists are reproducible, rigorous and transparent.  As well as informing the content of the training we will be signposting to this book as an invaluable reference for our students as they take their first steps into the world of Discrete Event Simulation" - **Dr Daniel Chalk, Senior Research Fellow at the University of Exeter**.

* **Coding for Reproducible Research (R environments)**  
  Material from the DES RAP Book has been adapted for use in the R environments module of the [Coding for Reproducible Research](https://coding-for-reproducible-research.github.io/CfRR_Courses/short_courses/r_environments.html) Training Programme from the University of Exeter.
