---
title: ❌ Entity generation
filters:
  - line-highlight
bibliography: patients_resources/references.bib
---

{{< include ../../scripts/_reticulate-setup.md >}}

::: {.pale-blue}

🎯 **Objectives**

This page creates a simple model that samples arrivals, with inspiration from @hsma_des_book.

* **🚶 Creating a simple simulation model with arrivals:** Build a basic model that simulates random arrival times.
* **📉 Distribution registry:** Alternative set-up that organises all simulation distributions in one place.

[🔗](../intro/guidelines.qmd) **Reproducibility guidelines**

Entity generation is not directly addressed by the guidelines, but is an essential step in building DES.

:::

<br>

::: {.python-content}

On this page, we will start creating a very simple simulation model using `simpy`.

:::
::: {.r-content}

On this page, we will start creating a very simple simulation model using `simmer`.

:::

As it builds on their content, it is recommended you review the following pages first:

* [Parameters from script](../inputs/parameters_script.qmd).
* [Parameters from file](../inputs/parameters_file.qmd).
* [Randomness](distributions.qmd).

The examples here will use the following packages. These should already be available if you followed the environment setup in the "*🧪 Test yourself*" section of the [Environments](../setup/environment.qmd) page. If not, please install them before continuing.

::: {.python-content}

```{python}
import numpy as np
import simpy
from sim_tools.distributions import DistributionRegistry, Exponential
```

:::

::: {.r-content}

```{r}
# library(simmer)
```

:::

## 🚶 Creating a simple simulation model with arrivals

Before writing any code, it's important that you have defined a conceptual model of the process to guide design of your simulation, and that the necessary parameters are defined. With these essentials in place, the process of building the simulation can start.

The best approach is to build the model **step by step**, testing and understanding each component before adding more complexity. Typically, the first step is to write code that **generates arrivals into the system**.

::: {.python-content}

### Parameter class

First, we need an object with the simulation parameters. Here, we use a class similar to that on the [Parameters from script](../inputs/parameters_script.qmd) page, with some tweaks to the parameters contained.

```{python}
class Parameters:
    """
    Parameter class.
    """
    def __init__(
        self, interarrival_time=5, consultation_time=10,
        run_length=50
    ):
        """
        Initialise Parameters instance.

        Parameters
        ----------
        interarrival_time : float
            Time between arrivals (minutes).
        consultation_time : float
            Length of consultation (minutes).
        run_length : int
            Simulation run length (minutes).
        """
        self.interarrival_time = interarrival_time
        self.consultation_time = consultation_time
        self.run_length = run_length
```

### Model class

We'll create a class for the model. Classes are useful as they can keep track of state and group logic (see [Code organisation](../setup/code_structure.qmd) page for more).

This class is explained line by line below.

```{python}
class Model:
    """
    Simulation model.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    run_number : int
        Run number for random seed generation.
    env : simpy.Environment
        The SimPy environment for the simulation.
    arrival_dist : Exponential
        Distribution used to generate random patient inter-arrival times.
    """
    def __init__(self, param, run_number):
        """
        Create a new Model instance.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        run_number : int
            Run number for random seed generation.
        """
        self.param = param
        self.run_number = run_number

        # Create SimPy environment
        self.env = simpy.Environment()

        # Create a random seed sequence based on the run number
        ss = np.random.SeedSequence(self.run_number)
        seeds = ss.spawn(1)

        # Create an exponential distribution for patient inter-arrival times
        self.arrival_dist = Exponential(mean=self.param.interarrival_time,
                                        random_seed=seeds[0])

    def generate_arrivals(self):
        """
        Process that generates patient arrivals.
        """
        while True:
            # Sample and pass time to next arrival
            sampled_iat = self.arrival_dist.sample()
            yield self.env.timeout(sampled_iat)
            # Print arrival time
            print(f"Arrival at time: {self.env.now}")

    def run(self):
        """
        Run the simulation.
        """
        # Schedule arrival generator
        self.env.process(self.generate_arrivals())
        # Run the simulation
        self.env.run(until=self.param.run_length)
```

### Explaining the model class

```{.python}
def __init__(self, param, run_number):
    """
    Create a new Model instance.

    Parameters
    ----------
    param : Parameters
        Simulation parameters.
    run_number : int
        Run number for random seed generation.
    """
    self.param = param
    self.run_number = run_number
```

There are two arguments required by the initialiser: `param` and `run_number`.

The `param` argument accepts an instance of the `Parameters` object, which groups all necessary simulation values in one place. This minimises the number of arguments required by `Model`, as it only needs one input for parameters.

The `run_number` will be used when generating the random seeds. This is important when performing multiple replications, as it ensures each run gets a unique seed (see the [Replications](../output_analysis/n_reps.qmd) page for more details).

<br>

```{.python}
# Create SimPy environment
self.env = simpy.Environment()
```

A SimPy `Environment` is the main simulation container. Everything that happens in the simulation is managed inside this environment. It tracks the flow of time and manages when events, such as arrivals, should occur.

For example, when patient arrivals are added, the environment is responsible for controlling their timing and execution.

<br>

```{.python}
# Create a random seed sequence based on the run number
ss = np.random.SeedSequence(self.run_number)
seeds = ss.spawn(1)
```

A random seed sequence is created based on the `run_number`.

<br>

```{.python}
# Create an exponential distribution for patient inter-arrival times
self.arrival_dist = Exponential(mean=self.param.interarrival_time,
                                random_seed=seeds[0])
```

We've used the `Exponential` distribution from `sim-tools` to generate inter-arrival times for patients.

<br>

```{.python}
def generate_arrivals(self):
    """
    Process that generates patient arrivals.
    """
    while True:
        # Sample and pass time to next arrival
        sampled_iat = self.arrival_dist.sample()
```

The `generate_arrivals` method is where patient arrivals are produced throughout the model run.

Using `while True` ensures the arrival generator continues to cycle and create new arrivals until the overall simulation time limit is reached.

Each time the loop cycles, it draws the next inter-arrival time from the exponential distribution, waits for that interval, and then triggers an arrival event.

<br>

```{.python}
yield self.env.timeout(sampled_iat)
```

The statement `yield self.env.timeout(sampled_iat)` is how the simulation waits between successive arrivals. It tells the SimPy environment to pause this arrivals process for the sampled time interval.

<br>

```{.python}
# Print arrival time
print(f"Arrival at time: {self.env.now}")
```

Printing the time of each arrival gives a quick and visible check that the arrival process is working as expected. For now, simple print statements are effective, but this can later be replaced by a more sophisticated logging approach (see [Logging](../verification_validation/logs.qmd)).

<br>

```{.python}
def run(self):
    """
    Run the simulation.
    """
    # Schedule arrival generator
    self.env.process(self.generate_arrivals())
```

Our final method in `Model` is `run`, which is responsible for setting up and running the simulation itself.

Before running the simulation, we have to tell SimPy that the process for creating arrivals should be managed as an "event generator" by calling `self.env.process()`. SimPy will now keep track of the arrival process and schedule its actions (timeouts and events) according to the rules laid out in our method.

<br>

```{.python}
# Run the simulation
self.env.run(until=self.param.run_length)
```

The simulation is now ready to go! We run it by calling `self.env.run()`, which will run the scheduled events until the desired end time is reached (taken from the `Parameters` object);

### Run the model

To try running the model, set up the parameters and model objects as shown, then call `run()`.

```{python}
param = Parameters()
model = Model(param=param, run_number=0)
model.run()
```

:::

::: {.r-content}

TODO

<!--TODO:

https://github.com/pythonhealthdatascience/pydesrap_stroke/blob/3a95ba490ad2807ce3f4fe72bf43d4ec639e9788/simulation/simulation.py

for r, when constructing, need to add to importfrom, then run devtoolsdocument, then loadall, then try it out
otherwise it won't find the stuff you importfrom if dont document first as needs to add to namespace

consider: often logging at this early stage... python print().... simmer verbose=True...

-->

:::

## 📉 Distribution registry

::: {.python-content}

In more advanced models, you may need multiple different random distributions (e.g., for arrivals, consultations, transfers, service times). Managing these with individual distribution objects quickly becomes tedious and can clutter your code.

The `DistributionRegistry` class from `sim-tools` provides a structured way to organise all your distributions. Instead of instantiating each distribution separately, you define them in a single configuration dictionary and let the registry handle the set-up.

This will feel excessive for our basic example, but having a distribution registry can make things easier for larger models.

### Changes in `Parameter` class

In the `Parameters` class, distributions are now specified in a dictionary called `dist_config`. Each entry describes the distribution type and its parameters.

```{python}
class Parameters:
    """
    Parameter class.
    """
    def __init__(
        self, interarrival_time=5, consultation_time=10,
        run_length=50
    ):
        """
        Initialise Parameters instance.

        Parameters
        ----------
        dist_config : dict  #<<
            Holds all distribution specifications.  #<<
        run_length : int
            Simulation run length (minutes).
        """
        self.dist_config = {  #<<
            "interarrival_time": {  #<<
                "class_name": "Exponential",  #<<
                "params": {"mean": interarrival_time}  #<<
            },  #<<
            "consultation_time": {  #<<
                "class_name": "Exponential",  #<<
                "params": {"mean": consultation_time}  #<<
            },  #<<
        }  #<<
        self.run_length = run_length
```

<!--TODO: should it be lockeddict? i do in pydesrapstroke... and i have covered it...-->

### Changes in `Model` class

The model now uses `DistributionRegistry.create_batch()` to set up all required distributions at once.

This creates a dictionary and we can access specific distributions via e.g., `self.dist["interarrival_time"]`.

```{python}
class Model:
    """
    Simulation model.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    run_number : int
        Run number for random seed generation.
    env : simpy.Environment
        The SimPy environment for the simulation.
    arrival_dist : Exponential
        Distribution used to generate random patient inter-arrival times.
    """
    def __init__(self, param, run_number):
        """
        Create a new Model instance.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        run_number : int
            Run number for random seed generation.
        """
        self.param = param
        self.run_number = run_number

        # Create SimPy environment
        self.env = simpy.Environment()

        # Create a random seed sequence based on the run number
        ss = np.random.SeedSequence(self.run_number)
        seeds = ss.spawn(1)

        # Create all the distributions  #<<
        self.dist = DistributionRegistry.create_batch(  #<<
            config=dict(self.param.dist_config), main_seed=self.run_number  #<<
        )  #<<
        print(self.dist)

    def generate_arrivals(self):
        """
        Process that generates patient arrivals.
        """
        while True:
            # Sample and pass time to next arrival
            sampled_iat = self.dist["interarrival_time"].sample()  #<<
            yield self.env.timeout(sampled_iat)
            # Print arrival time
            print(f"Arrival at time: {self.env.now}")

    def run(self):
        """
        Run the simulation.
        """
        # Schedule arrival generator
        self.env.process(self.generate_arrivals())
        # Run the simulation
        self.env.run(until=self.param.run_length)
```

### Run the model

We can see that results are consistent with before.

```{python}
param = Parameters()
model = Model(param=param, run_number=0)
model.run()
```

:::

## 🔍 Explore the example models

<div class="h3-tight"></div>

### 🩺 Nurse visit simulation

:::: {.python-content}

{{< include ../../html/pydesrapmms.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** | `simulation/param.py`<br>`simulation/model.py` |
| **What to look for?** | The structure is similar to the first example on this page. The `Param` class (in `param.py`) stores all simulation settings, including `patient_inter`. The `Model` class (in `model.py`) sets up the simulation environment, initialises the required distribution for arrivals, and `generate_patient_arrivals()` samples inter-arrival times and triggers arrivals. |
| **Why it matters?** | The structure is suitable as the model is simple, with just one patient type arriving. |
: {tbl-colwidths="[20,80]"}
:::
::::

:::: {.r-content}

{{< include ../../html/rdesrapmms.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** |  |
| **What to look for?** |  |
| **Why it matters?** |  |
: {tbl-colwidths="[20,80]"}
:::
::::

### 🧠 Stroke pathway simulation

:::: {.python-content}

{{< include ../../html/pydesrapstroke.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** | `simulation/parameters.py`<br>`simulation/model.py` |
| **What to look for?** | The model uses a `DistributionRegistry` to manage multiple distributions for different entities and processes. The `dist_config` from `Param` (`parameters.py`) is used by the registry. The dictionary of distribution is nested for easy access - restructured as `dist[type][unit][patient]`. Arrivals are generated using the adaptable `patient_generator()` method, which selects the appropriate distribution to sample based on patient type and unit. |
| **Why it matters?** | Using a distribution registry and a flexible arrival generator method avoids repeated, hard-coded logic and simplifies maintenance in this more complex model. |
: {tbl-colwidths="[20,80]"}
:::
::::

:::: {.r-content}

{{< include ../../html/rdesrapstroke.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** |  |
| **What to look for?** |  |
| **Why it matters?** |  |
: {tbl-colwidths="[20,80]"}
:::
::::

## 🧪 Test yourself

Have a go at setting up a basic simulation model with entity generation, while following good package organisation.

**Task:**

::: {.python-content}

1. **Copy the code:** Take `Parameters` and `Model` class from above (simple or with distribution registry) and place them in modules within your package (e.g., `parameters.py` and `model.py` within a `simulation/` folder).

2. **Set up a notebook:** Create a new notebook file (e.g., `notebooks/run_model.ipynb`).

3. **Import and run the model:** From your notebook, import `Parameters` and `Model` from your package and run the model.

:::

::: {.r-content}

1. TODO

2. TODO

3. TODO

:::

4. **Experiment:**
    * If you copied the simple versions, try using the versions with distribution registries, and vice versa.
    * Try different seeds by varying `run_number` in your notebook.
    * Try adding a new arrival type - add the distribution parameters in `Parameters`, and see how you can sample from them in `Model`.

::: {.callout-tip}

If you are unsure how to organise these classes as a package, checkout out the [Structuring as a Package](../setup/package.qmd) page for a tutorial on this.

:::

## 📙 References

::: {#refs}
:::

<br><br>
