---
title: ❌ Entity processing
filters:
  - line-highlight
---

{{< include ../../scripts/_reticulate-setup.md >}}

:::: {.pale-blue}

🎯 **Objectives**

::: {.python-content}
This page adds a process to the model (which uses a resource), with inspiration from Rosser et al. ([2025](https://des.hsma.co.uk/)).
:::
::: {.r-content}
This page adds a process to the model (which uses a resource).
:::

* **🥼 Adding a consultation with a doctor to the model:**

[🔗](../intro/guidelines.qmd) **Reproducibility guidelines**

Entity processing is not directly addressed by the guidelines, but is an essential step in building DES.

::::

<br>

::: {.cream}

⚠️ This page continues on from the [Entity generation](patients.qmd) page - work through that first!

:::

<br>


## 🥼 Adding a consultation with a doctor to the model

On the last page, we created a simple model with patient arrivals. As we continue building our model iteratively, we now add add a feature typical fo DES models: a process using a resource. In this case, a consultation with a doctor.

Required packages:

::: {.python-content}

```{python}
import numpy as np
import simpy
from sim_tools.distributions import Exponential
```

:::

::: {.r-content}

```{r}
library(simmer)
```

:::

::: {.python-content}

### Changes to the `Parameter` class

There are two new parameters: `consultation_time` and `number_of_doctors`.

```{python}
class Parameters:
    """
    Parameter class.

    Attributes
    ----------
    interarrival_time : float
        Mean time between arrivals (minutes).
    consultation_time : float                                               #<<
        Mean length of doctor's consultation (minutes).                     #<<
    number_of_doctors : int                                                 #<<
        Number of doctors.                                                  #<<
    run_length : int
        Total duration of simulation (minutes).
    """
    def __init__(
        self, interarrival_time=5, consultation_time=10,                    #<<
        number_of_doctors=3, run_length=50                                  #<<
    ):
        """
        Initialise Parameters instance.

        Parameters
        ----------
        interarrival_time : float
            Time between arrivals (minutes).
        consultation_time : float                                           #<<
            Length of consultation (minutes).                               #<<
        number_of_doctors : int                                             #<<
            Number of doctors.                                              #<<
        run_length : int
            Total duration of simulation (minutes).
        """
        self.interarrival_time = interarrival_time
        self.consultation_time = consultation_time                          #<<
        self.number_of_doctors = number_of_doctors                          #<<
        self.run_length = run_length
```

### `Patient` class

No changes needed!

```{python}
class Patient:
    """
    Represents a patient.

    Attributes
    ----------
    patient_id : int
        Unique patient identifier.
    """
    def __init__(self, patient_id):
        """
        Initialises a new patient.

        Parameters
        ----------
        patient_id : int
            Unique patient identifier.
        """
        self.patient_id = patient_id
```

### Changes to the `Model` class

These changes are explained below...

```{python}
class Model:
    """
    Simulation model.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    run_number : int
        Run number for random seed generation.
    env : simpy.Environment
        The SimPy environment for the simulation.
    doctor : simpy.Resource                                                 #<<
        SimPy resource representing doctors.                                #<<
    patients : list
        List of Patient objects.
    arrival_dist : Exponential
        Distribution used to generate random patient inter-arrival times.
    consult_dist : Exponential                                              #<<
        Distribution used to generate length of a doctor's consultation.    #<<
    """
    def __init__(self, param, run_number):
        """
        Create a new Model instance.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        run_number : int
            Run number for random seed generation.
        """
        self.param = param
        self.run_number = run_number

        # Create SimPy environment
        self.env = simpy.Environment()

        # Create resource
        self.doctor = simpy.Resource(                                       #<<
            self.env, capacity=self.param.number_of_doctors                 #<<
        )                                                                   #<<

        # Create a random seed sequence based on the run number
        ss = np.random.SeedSequence(self.run_number)
        seeds = ss.spawn(2)                                                 #<<

        # Create patient list
        self.patients = []

        # Initialise distributions
        self.arrival_dist = Exponential(mean=self.param.interarrival_time,
                                        random_seed=seeds[0])
        self.consult_dist = Exponential(mean=self.param.consultation_time,  #<<
                                        random_seed=seeds[1])               #<<

    def generate_arrivals(self):
        """
        Process that generates patient arrivals.
        """
        while True:
            # Sample and pass time to next arrival
            sampled_iat = self.arrival_dist.sample()
            yield self.env.timeout(sampled_iat)

            # Create a new patient
            patient = Patient(patient_id=len(self.patients)+1)
            self.patients.append(patient)

            # Print arrival time
            print(f"Patient {patient.patient_id} arrives " +
                  f"at time: {self.env.now:.3f}")

            # Start process of consultation                                 #<<
            self.env.process(self.consultation(patient))                    #<<

    def consultation(self, patient):                                        #<<
        """                                                                 #<<
        Process that simulates a consultation.                              #<<

        Parameters                                                          #<<
        ----------                                                          #<<
        patient :                                                           #<<
            Instance of the Patient() class representing a single patient.  #<<
        """                                                                 #<<
        with self.doctor.request() as req:                                  #<<
            yield req                                                       #<<
            print(f"Patient {patient.patient_id} starts consultation " +    #<<
                  f"at: {self.env.now:.3f}")                                #<<
            time_with_doctor = self.consult_dist.sample()                   #<<
            yield self.env.timeout(time_with_doctor)                        #<<

    def run(self):
        """
        Run the simulation.
        """
        # Schedule arrival generator
        self.env.process(self.generate_arrivals())
        # Run the simulation
        self.env.run(until=self.param.run_length)
```

1. Take `penguins`, and then,

#### Explaining the changes to `Model`

```{.python}
# Create resource
self.doctor = simpy.Resource(                                       
    self.env, capacity=self.param.number_of_doctors                 
)
```

TODO

<br>

```{.python}
seeds = ss.spawn(2)
```

<br>

```{.python}
self.consult_dist = Exponential(mean=self.param.consultation_time,  
                                random_seed=seeds[1])
```

### Run the model

```{python}
param = Parameters()
model = Model(param=param, run_number=0)
model.run()
```

:::

## 🔗 Further information

::: {.python-content}

* "[HSMA - little book of DES](https://des.hsma.co.uk/)" from Sammi Rosser, Dan Chalk and Amy Heather 2025

    *Introduction to writing discrete event simulation models for healthcare in SimPy.*

:::

::: {.r-content}

N/A

:::

<br><br>
