---
title: Feedback
date: "2025-10-24T14:38:09+01:00"
---

<br>

::: {.pale-blue}

We are excited to hear from people who have used this book. Your feedback and experience can help shape it for future readers and the broader healthcare simulation community.

:::

## How to comment

At the bottom of every page in this book, you'll find a comment section powered by **Giscus**. After signing in with your GitHub account, you can:

* Comment on individual pages to share insights, ask questions, or flag typos/bugs.
* Leave a comment here (or on the home/conclusion pages) to give feedback about the book overall.

**We'd love to hear from you**. If you've used the book, let us know! What worked well? What could be improved? Share any questions, suggestions, success stories, challenges, or ideas for new content.

**We'd also be really interested to know how you first found this resource.**   When you leave feedback, please tell us how you heard about the DES RAP Book. This helps us understand how easy it is for new learners to find the material.

## Want to contribute?

Leave a comment via Giscus.

Alternatively, you can open a GitHub issue for bugs, feature requests, or suggestions: [github.com/pythonhealthdatascience/des_rap_book/issues](https://github.com/pythonhealthdatascience/des_rap_book/issues)

Interested in contributing directly? Check out `CONTRIBUTING.md` in the repository for the process - fork, edit locally, and submit a pull request.

All contributions are acknowledged in the README via the all-contributors system.

## Contact information

Prefer email instead? Reach out to the STARS team - you can contact the following team members about this site:

* Amy Heather: [a.heather2@exeter.ac.uk](mailto:a.heather2@exeter.ac.uk)
* Tom Monks: [t.m.w.monks@exeter.ac.uk](mailto:t.m.w.monks@exeter.ac.uk)
* Alison Harper: [a.l.harper@exeter.ac.uk](mailto:a.l.harper@exeter.ac.uk)
* Nav Mustafee: [n.mustafee@exeter.ac.uk](mailto:n.mustafee@exeter.ac.uk)

This book is part of the **STARS (Sharing Tools and Artefacts for Reusable and Reproducible Simulations)** project, supported by the Medical Research Council from 1st May 2024 to 31st October 2026.

<br><br>
