---
format:
  html:
    css: guidelines_style.css
    crossrefs-hover: false
---

# Reproducibility guidelines {#sec-guidelines}

There's lots of guidance to support reproducible research. This book focuses specifically on healthcare discrete-event simulation (DES) models, drawing from two particularly relevant frameworks:

* The recommendations from Heather et al. 2025.
* The NHS Reproducible Analytical Pipeline (RAP) Maturity Framework.

This book walks through how to address all aspects of these guidelines, and the links below (🔗) take you to relevant pages with detailed guidance on each topic.

## Reproducibility recommendations from Heather et al. 2025

As part of the project STARS (Sharing Tools and Artefacts for Reproducible Simulations), a series of computational reproducibility assessments were conducted by Heather et al. 2025. From these, several recommendations were shared to support reproducibility of healthcare discrete-event simulation (DES) models, as described in:

> Heather, A. Monks, T. Harper, A. Mustafee, N. Mayne, A. On the reproducibility of discrete-event simulation studies in health research: an empirical study using open models (2025). arxiv. <https://doi.org/10.48550/arXiv.2501.13137>.

Those marked with a star (⭐) were identified as having the greatest impact in Heather et al. 2025.

### Recommendations to support reproduction

| Recommendation | Chapter |
| -- | - |
| **Set-up** | 
| Share code with an open licence ⭐  | <span class="section-link">@sec-licence</span> |
| Link publication to a specific version of the code | <span class="section-link">@sec-changelog</span> |
| List dependencies and versions | <span class="section-link">@sec-environment</span> |
| **Running the model** |
| Provide code for all scenarios and sensitivity analyses ⭐ | <span class="section-link">@sec-scenarios</span> |
| Ensure model parameters are correct ⭐ | <span class="section-link">@sec-full_run</span> |
| Control randomness | <span class="section-link">@sec-distributions</span> |
| **Outputs** |
| Include code to calculate all required model outputs ⭐ | <span class="section-link">@sec-outputs</span> |
| Include code to generate the tables, figures, and other reported results ⭐ | <span class="section-link">@sec-tables_figures</span> |

### Recommendations to support troubleshooting and reuse

| Recommendation | Chapter |
| -- | - |
| **Design** |
| Separate model code from applications | ❓ |
| Avoid hard-coded parameters | <span class="section-link">@sec-parameters</span> |
| Minimise code duplication | <span class="section-link">@sec-code_structure</span> |
| **Clarity** |
| Comment sufficiently | <span class="section-link">@sec-docstrings</span> |
| Ensure clarity and consistency in the model results tables | <span class="section-link">@sec-outputs</span> |
| Include run instructions | <span class="section-link">@sec-documentation</span> |
| State run times and machine specifications | <span class="section-link">@sec-documentation</span> |
| **Functionality** |
| Optimise model run time | <span class="section-link">@sec-parallel</span> |
| Save outputs to a file | <span class="section-link">@sec-tables_figures</span> |
| Avoid excessive output files | ❓ |
| Address large file sizes | ❓ |

## 'Levels of RAP' Maturity Framework

The following framework has been directly copied from the RAP Community of Practice repository/website: [NHS RAP Levels of RAP Framework](https://nhsdigital.github.io/rap-community-of-practice/introduction_to_RAP/levels_of_RAP/).

This framework is maintained by the NHS RAP Community of Practice and is © 2024 Crown Copyright (NHS England), shared by them under the terms of the [Open Government 3.0 licence](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/).

The specific version of the framework copied below is that from commit [2549256](https://github.com/NHSDigital/rap-community-of-practice/commit/2549256498886d6d7ea4cdb736e2a2864c8bb461) (9th September 2024).

### 🥉 Baseline

RAP fundamentals offering resilience against future change.

| Criteria | Chapter |
| -- | - |
| Data produced by code in an open-source language (e.g., Python, R, SQL). | <span class="section-link">@sec-foss</span> |
| Code is version controlled (see [Git basics](https://nhsdigital.github.io/rap-community-of-practice/training_resources/git/introduction-to-git/) and [using Git collaboratively](https://nhsdigital.github.io/rap-community-of-practice/training_resources/git/using-git-collaboratively/) guides). | <span class="section-link">@sec-version</span> |
| Repository includes a README.md file (or equivalent) that clearly details steps a user must follow to reproduce the code (use [NHS Open Source Policy section on Readmes](https://github.com/nhsx/open-source-policy/blob/main/open-source-policy.md#b-readmes) as a guide). | <span class="section-link">@sec-documentation</span> |
| Code has been [peer reviewed](https://nhsdigital.github.io/rap-community-of-practice/implementing_RAP/workflow/code-review/). | <span class="section-link">@sec-peer_review</span> |
| Code is [published in the open](https://nhsdigital.github.io/rap-community-of-practice/implementing_RAP/publishing_code/how-to-publish-your-code-in-the-open/) and linked to & from accompanying publication (if relevant). | <span class="section-link">@sec-archive</span> |

### 🥈 Silver

Implementing best practice by following good analytical and software engineering standards.

Meeting all of the above requirements, plus:

| Criteria | Chapter |
| -- | - |
| Outputs are produced by code with minimal manual intervention. | <span class="section-link">@sec-full_run</span> |
| Code is well-documented including user guidance, explanation of code structure & methodology and [docstrings](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/python-functions/#documentation) for functions. | <span class="section-link">@sec-documentation</span> <span class="section-link">@sec-docstrings</span> |
| Code is well-organised following [standard directory format](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/project-structure-and-packaging/). | <span class="section-link">@sec-package</span> |
| [Reusable functions](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/python-functions/) and/or classes are used where appropriate. | <span class="section-link">@sec-code_structure</span> |
| Code adheres to agreed coding standards (e.g PEP8, [style guide for Pyspark](https://nhsdigital.github.io/rap-community-of-practice/training_resources/pyspark/pyspark-style-guide/)). | <span class="section-link">@sec-linting</span> |
| Pipeline includes a testing framework ([unit tests](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/unit-testing/), [back tests](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/backtesting/)). | <span class="section-link">@sec-tests</span> |
| Repository includes dependency information (e.g. [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files), [PipFile](https://github.com/pypa/pipfile/blob/main/README.rst), [environment.yml](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/virtual-environments/conda/)). | <span class="section-link">@sec-environment</span> |
| [Logs](https://nhsdigital.github.io/rap-community-of-practice/training_resources/python/logging-and-error-handling/) are automatically recorded by the pipeline to ensure outputs are as expected. | <span class="section-link">@sec-logs</span> |
| Data is handled and output in a [Tidy data format](https://medium.com/@kimrodrikwa/untidy-data-a90b6e3ebe4c). | <span class="section-link">@sec-outputs</span> |

### 🥇 Gold 

Analysis as a product to further elevate your analytical work and enhance its reusability to the public.

Meeting all of the above requirements, plus:

| Criteria | Chapter |
| -- | - |
| Code is fully [packaged](https://packaging.python.org/en/latest/). | <span class="section-link">@sec-package</span> |
| Repository automatically runs tests etc. via CI/CD or a different integration/deployment tool e.g. [GitHub Actions](https://docs.github.com/en/actions). | <span class="section-link">@sec-github_actions</span> |
| Process runs based on event-based triggers (e.g., new data in database) or on a schedule. | N/A |
| Changes to the RAP are clearly signposted. E.g. a changelog in the package, releases etc. (See gov.uk info on [Semantic Versioning](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/versioning.md)). | <span class="section-link">@sec-changelog</span> |