---
title: ❌ Documentation
---

:::: {.pale-blue}

**Learning objectives:**

* TODO

**Relevant reproducibility guidelines:**

* STARS Reproducibility Recommendations: Include run instructions.
* STARS Reproducibility Recommendations: State run times and machine specifications.
* NHS Levels of RAP (🥉): Repository includes a README.md file (or equivalent) that clearly details steps a user must follow to reproduce the code (use NHS Open Source Policy section on Readmes as a guide).
* NHS Levels of RAP (🥈): Code is well-documented including user guidance, explanation of code structure & methodology and docstrings for functions.

**Pre-reading:**

TODO

**Required packages:**

TODO

::::

## Explore the example models

<div class="h3-tight"></div>

### Nurse visit simulation

:::: {.python-content}

{{< include ../../html/pydesrapmms.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key files** | |
| **What to look for?** | |
| **Why it matters?** | |
: {tbl-colwidths="[20,80]"}
:::

::::

:::: {.r-content}

{{< include ../../html/rdesrapmms.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key files** | |
| **What to look for?** | |
| **Why it matters?** | |
: {tbl-colwidths="[20,80]"}
:::

::::

### Stroke pathway simulation

:::: {.python-content}

{{< include ../../html/pydesrapstroke.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key files** | |
| **What to look for?** | |
| **Why it matters?** | |
: {tbl-colwidths="[20,80]"}
:::

::::

:::: {.r-content}

{{< include ../../html/rdesrapstroke.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key files** | |
| **What to look for?** | |
| **Why it matters?** | |
: {tbl-colwidths="[20,80]"}
:::

::::

## Test yourself

<!--TODO-->

<br><br>
