---
title: ❌ Performance measures
filters:
  - line-highlight
---

{{< include ../../scripts/_reticulate-setup.md >}}

:::: {.pale-blue}

**Learning objectives:**

* Learn **how to record various performance measures** within the simulation model.

**Relevant reproducibility guidelines:**

* STARS Reproducibility Recommendations (⭐): Include code to calculate all required model outputs
* STARS Reproducibility Recommendations: Ensure clarity and consistency in the model results tables.
* NHS Levels of RAP (🥈): Data is handled and output in a Tidy data format.

**Pre-reading:**

This page continues on from: [Initialisation bias](warmup.qmd).

> *Entity generation → Entity processing → Initialisation bias → Performance measures*

**Required packages:**

These should be available from environment setup in the "🧪 Test yourself" section of [Environments](../setup/environment.qmd). 

::: {.python-content}

```{python}
import numpy as np
import pandas as pd
import simpy
from sim_tools.distributions import Exponential
```

:::

::: {.r-content}

```{r}
library(simmer)
```

:::

::::

<br>

Where relevant, we have included **corresponding terms from queueing theory** for each measure.

> **What is queueing theory?** Queueing theory is a field of mathematics that analyses queues under strict assumptions, and is suitable for simple well-characterised systems. Discrete event simulation (DES) can be applied in similar ways (e.g., replicating classic queueing models like M/M/s), but more often extends beyond simple theory to handle a wider range of arrival and service patterns and more complex resource constraints.

<!--TODO: interval audit v.s. not... use of interval audit... etc.etc.-->

## ✏️ Preparation for results collection

::: {.python-content}

Before we start calculating any simulation performance measures, some set-up is required. This includes initial changes to `Parameters` and `Model`, and the creation of a new class: `Runner`.

:::

::: {.r-content}

Before we start calculating any simulation performance measures, some set-up is required.

:::

:::: {.callout title="▶&nbsp;&nbsp;View preparation steps" collapse="true"}

::: {.python-content}

### Parameter class

Set `verbose` to `False` in the `Parameters` class. This lets the workflow focus on the calculated results rather than individual patient activities.

```{python}
{{< include outputs_resources/parameters.py >}}
```

### Patient class

No changes are required for `Patient` at this stage.

```{python}
#| echo: false
{{< include outputs_resources/patient.py >}}
```

### Model class

We need to update the `Model` class so its `run` method returns a list of patient attributes. This makes patient-level data easy to analyse after simulation runs.

```{python}
{{< include outputs_resources/model.py >}}
```

### Runner class

We're also introducing a new `Runner` class, responsible for running simulations and performing results calculations. This keeps calculation logic separate from the core modelling code. Also, this class will be modified to perform multiple model runs on the [Replications](n_reps.qmd) page.

The basic structure of `Runner` is as follows. It initialises with simulation parameters, runs the model for a single replication, and organises results into separate patient-level and run-level outputs.

```{python}
{{< include outputs_resources/runner.py >}}
```

Running the model via `Runner` produces our new structured results.

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["patient"])
print(result["run"])
```

Now we're ready to record some performance measures. 😎

:::

::: {.r-content}

:::

::::

## 🚶‍♀️ Total arrivals

:::: {.callout title="▶&nbsp;&nbsp;View how to record the total arrivals" collapse="true"}

::: {.python-content}

<br>

Recording the total number of arrivals is super simple! We just need to find the **length of the patient list**.

### Parameter class

No changes required.

```{python}
#| echo: false
{{< include outputs_resources/parameters.py >}}
```

### Patient class

No changes required.

```{python}
#| echo: false
{{< include outputs_resources/patient.py >}}
```

### Model class

No changes required.

```{python}
#| echo: false
{{< include outputs_resources/model.py >}}
```

### Runner class

```{python}
class Runner:
    """
    Run the simulation.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    """
    def __init__(self, param):
        """
        Initialise a new instance of the Runner class.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        """
        self.param = param

    def run_single(self, run):
        """
        Runs the simulation once and performs results calculations.

        Parameters
        ----------
        run : int
            Run number for the simulation.

        Returns
        -------
        dict
            Contains patient-level results and results from each run.
        """
        model = Model(param=self.param, run_number=run)
        model.run()

        # Patient results
        patient_results = pd.DataFrame(model.results_list)
        patient_results["run"] = run

        # Run results
        run_results = {
            "run_number": run,
            "arrivals": len(patient_results)#<<
        }

        return {
            "patient": patient_results,
            "run": run_results
        }
```

### Run the model

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["run"])
```

:::

::: {.r-content}

:::

::::

## ⏱️ Mean wait time

> **Corresponding term in queueing theory:** Average wait time in queue, $\\W_q$

:::: {.callout title="▶&nbsp;&nbsp;View how to record the mean wait time" collapse="true"}

::: {.python-content}

<br>

For this measure, we need to record the **time each patient spent waiting** for the doctor.

### Parameter class

No changes required.

```{python}
#| echo: false
{{< include outputs_resources/parameters.py >}}
```

### Patient class

A new attribute `wait_time` is add to the `Patient` class.

```{python}
class Patient:
    """
    Represents a patient.

    Attributes
    ----------
    patient_id : int
        Unique patient identifier.
    period : str
        Arrival period (warm up or data collection) with emoji.
    wait_time : float#<<
        Time spent waiting for the doctor (minutes).#<<
    """
    def __init__(self, patient_id, period):
        """
        Initialises a new patient.

        Parameters
        ----------
        patient_id : int
            Unique patient identifier.
        period : str
            Arrival period (warm up or data collection) with emoji.
        """
        self.patient_id = patient_id
        self.period = period
        self.wait_time = np.nan#<<
```

### Model class

Within `Model.consultation()`, the start time of the consultation is recorded (`start_wait`). When the resource request has been granted, the time elapsed is saved under `patient.wait_time`.

```{python}
class Model:
    """
    Simulation model.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    run_number : int
        Run number for random seed generation.
    env : simpy.Environment
        The SimPy environment for the simulation.
    doctor : simpy.Resource
        SimPy resource representing doctors.
    patients : list
        List of Patient objects.
    results_list : list
        List of dictionaries with the attributes of each patient.
    arrival_dist : Exponential
        Distribution used to generate random patient inter-arrival times.
    consult_dist : Exponential
        Distribution used to generate length of a doctor's consultation.
    """
    def __init__(self, param, run_number):
        """
        Create a new Model instance.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        run_number : int
            Run number for random seed generation.
        """
        self.param = param
        self.run_number = run_number

        # Create SimPy environment
        self.env = simpy.Environment()

        # Create resource
        self.doctor = simpy.Resource(
            self.env, capacity=self.param.number_of_doctors
        )

        # Create a random seed sequence based on the run number
        ss = np.random.SeedSequence(self.run_number)
        seeds = ss.spawn(2)

        # Set up attributes to store results
        self.patients = []
        self.results_list = []

        # Initialise distributions
        self.arrival_dist = Exponential(mean=self.param.interarrival_time,
                                        random_seed=seeds[0])
        self.consult_dist = Exponential(mean=self.param.consultation_time,
                                        random_seed=seeds[1])

    def generate_arrivals(self):
        """
        Process that generates patient arrivals.
        """
        while True:
            # Sample and pass time to next arrival
            sampled_iat = self.arrival_dist.sample()
            yield self.env.timeout(sampled_iat)

            # Check whether arrived during warm-up or data collection
            if self.env.now < self.param.warm_up_period:
                period = "\U0001F538 WU"
            else:
                period = "\U0001F539 DC"

            # Create a new patient
            patient = Patient(patient_id=len(self.patients)+1,
                              period=period)
            self.patients.append(patient)

            # Print arrival time
            if self.param.verbose:
                print(f"{patient.period} Patient {patient.patient_id} " +
                      f"arrives at time: {self.env.now:.3f}")

            # Start process of consultation
            self.env.process(self.consultation(patient))

    def consultation(self, patient):
        """
        Process that simulates a consultation.

        Parameters
        ----------
        patient :
            Instance of the Patient() class representing a single patient.
        """
        start_wait = self.env.now#<<
        # Patient requests access to a doctor (resource)
        with self.doctor.request() as req:
            yield req

            # Record how long patient waited before consultation#<<
            patient.wait_time = self.env.now - start_wait#<<

            if self.param.verbose:
                print(f"{patient.period} Patient {patient.patient_id} starts" +
                      f" consultation at: {self.env.now:.3f}")

            # Sample consultation duration and pass time spent with doctor
            time_with_doctor = self.consult_dist.sample()
            yield self.env.timeout(time_with_doctor)

    def reset_results(self):
        """
        Reset results.
        """
        self.patients = []

    def warmup(self):
        """
        Reset result collection after the warm-up period.
        """
        if self.param.warm_up_period > 0:
            # Delay process until warm-up period has completed
            yield self.env.timeout(self.param.warm_up_period)
            # Reset results variables
            self.reset_results()
            if self.param.verbose:
                print(f"Warm up period ended at time: {self.env.now}")

    def run(self):
        """
        Run the simulation.
        """
        # Schedule arrival generator and warm-up
        self.env.process(self.generate_arrivals())
        self.env.process(self.warmup())
        # Run the simulation
        self.env.run(until=(self.param.warm_up_period +
                            self.param.data_collection_period))
        # Create list of dictionaries containing each patient's attributes
        self.results_list = [x.__dict__ for x in self.patients]
```

### Runner class

The mean `wait_time` from the patients is calculated.

```{python}
class Runner:
    """
    Run the simulation.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    """
    def __init__(self, param):
        """
        Initialise a new instance of the Runner class.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        """
        self.param = param

    def run_single(self, run):
        """
        Runs the simulation once and performs results calculations.

        Parameters
        ----------
        run : int
            Run number for the simulation.

        Returns
        -------
        dict
            Contains patient-level results and results from each run.
        """
        model = Model(param=self.param, run_number=run)
        model.run()

        # Patient results
        patient_results = pd.DataFrame(model.results_list)
        patient_results["run"] = run

        # Run results
        run_results = {
            "run_number": run,
            "mean_wait_time": patient_results["wait_time"].mean()#<<
        }

        return {
            "patient": patient_results,
            "run": run_results
        }
```

### Run the model

We can see each patient's wait time in `result["patient"]`, and the mean wait time in `result["run"]`.

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["patient"])
print(result["run"])
```

:::

::: {.r-content}

:::

::::

## 🩺 Mean time in consultation

> **Corresponding term in queueing theory:** Service time, 1/$\mu$

:::: {.callout title="▶&nbsp;&nbsp;View how to record the mean time spent in the consultation" collapse="true"}

::: {.python-content}

### Parameter class

No changes required.

```{python}
#| echo: false
{{< include outputs_resources/parameters.py >}}
```

### Patient class

A new attribute `time_with_doctor` is add to the `Patient` class.

```{python}
class Patient:
    """
    Represents a patient.

    Attributes
    ----------
    patient_id : int
        Unique patient identifier.
    period : str
        Arrival period (warm up or data collection) with emoji.
    time_with_doctor : float#<<
        Time spent in consultation with a doctor (minutes).#<<
    """
    def __init__(self, patient_id, period):
        """
        Initialises a new patient.

        Parameters
        ----------
        patient_id : int
            Unique patient identifier.
        period : str
            Arrival period (warm up or data collection) with emoji.
        """
        self.patient_id = patient_id
        self.period = period
        self.time_with_doctor = np.nan#<<
```

### Model class

Within `Model.consultation()`, the sampled time with the doctor is saved under `patient.time_with_doctor`.

```{python}
class Model:
    """
    Simulation model.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    run_number : int
        Run number for random seed generation.
    env : simpy.Environment
        The SimPy environment for the simulation.
    doctor : simpy.Resource
        SimPy resource representing doctors.
    patients : list
        List of Patient objects.
    results_list : list
        List of dictionaries with the attributes of each patient.
    arrival_dist : Exponential
        Distribution used to generate random patient inter-arrival times.
    consult_dist : Exponential
        Distribution used to generate length of a doctor's consultation.
    """
    def __init__(self, param, run_number):
        """
        Create a new Model instance.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        run_number : int
            Run number for random seed generation.
        """
        self.param = param
        self.run_number = run_number

        # Create SimPy environment
        self.env = simpy.Environment()

        # Create resource
        self.doctor = simpy.Resource(
            self.env, capacity=self.param.number_of_doctors
        )

        # Create a random seed sequence based on the run number
        ss = np.random.SeedSequence(self.run_number)
        seeds = ss.spawn(2)

        # Set up attributes to store results
        self.patients = []
        self.results_list = []

        # Initialise distributions
        self.arrival_dist = Exponential(mean=self.param.interarrival_time,
                                        random_seed=seeds[0])
        self.consult_dist = Exponential(mean=self.param.consultation_time,
                                        random_seed=seeds[1])

    def generate_arrivals(self):
        """
        Process that generates patient arrivals.
        """
        while True:
            # Sample and pass time to next arrival
            sampled_iat = self.arrival_dist.sample()
            yield self.env.timeout(sampled_iat)

            # Check whether arrived during warm-up or data collection
            if self.env.now < self.param.warm_up_period:
                period = "\U0001F538 WU"
            else:
                period = "\U0001F539 DC"

            # Create a new patient
            patient = Patient(patient_id=len(self.patients)+1,
                              period=period)
            self.patients.append(patient)

            # Print arrival time
            if self.param.verbose:
                print(f"{patient.period} Patient {patient.patient_id} " +
                      f"arrives at time: {self.env.now:.3f}")

            # Start process of consultation
            self.env.process(self.consultation(patient))

    def consultation(self, patient):
        """
        Process that simulates a consultation.

        Parameters
        ----------
        patient :
            Instance of the Patient() class representing a single patient.
        """
        # Patient requests access to a doctor (resource)
        with self.doctor.request() as req:
            yield req

            if self.param.verbose:
                print(f"{patient.period} Patient {patient.patient_id} starts" +
                      f" consultation at: {self.env.now:.3f}")

            # Sample consultation duration and pass time spent with doctor
            patient.time_with_doctor = self.consult_dist.sample()#<<
            yield self.env.timeout(patient.time_with_doctor)#<<

    def reset_results(self):
        """
        Reset results.
        """
        self.patients = []

    def warmup(self):
        """
        Reset result collection after the warm-up period.
        """
        if self.param.warm_up_period > 0:
            # Delay process until warm-up period has completed
            yield self.env.timeout(self.param.warm_up_period)
            # Reset results variables
            self.reset_results()
            if self.param.verbose:
                print(f"Warm up period ended at time: {self.env.now}")

    def run(self):
        """
        Run the simulation.
        """
        # Schedule arrival generator and warm-up
        self.env.process(self.generate_arrivals())
        self.env.process(self.warmup())
        # Run the simulation
        self.env.run(until=(self.param.warm_up_period +
                            self.param.data_collection_period))
        # Create list of dictionaries containing each patient's attributes
        self.results_list = [x.__dict__ for x in self.patients]
```

### Runner class

The mean `time_with_doctor` from the patients is calculated.

```{python}
class Runner:
    """
    Run the simulation.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    """
    def __init__(self, param):
        """
        Initialise a new instance of the Runner class.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        """
        self.param = param

    def run_single(self, run):
        """
        Runs the simulation once and performs results calculations.

        Parameters
        ----------
        run : int
            Run number for the simulation.

        Returns
        -------
        dict
            Contains patient-level results and results from each run.
        """
        model = Model(param=self.param, run_number=run)
        model.run()

        # Patient results
        patient_results = pd.DataFrame(model.results_list)
        patient_results["run"] = run

        # Run results
        run_results = {
            "run_number": run,
            "mean_time_with_doctor": (#<<
                patient_results["time_with_doctor"].mean()#<<
            )#<<
        }

        return {
            "patient": patient_results,
            "run": run_results
        }
```

### Run the model

We can see each patient's consultation length in `result["patient"]`, and the mean time in `result["run"]`.

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["patient"])
print(result["run"])
```

:::

::: {.r-content}

:::

::::

## 👨‍⚕️ Mean doctor utilisation

> **Corresponding term in queueing theory:** Server utilisation, $\rho$

:::: {.python-content}

We have suggested two different approaches for measuring utilisation.

In this first approach...

::: {.callout title="▶&nbsp;&nbsp;View how to record utilisation" collapse="true"}

### Parameter class

No changes required.

```{python}
#| echo: false
{{< include outputs_resources/parameters.py >}}
```

### Patient class

No changes required.

```{python}
#| echo: false
{{< include outputs_resources/patient.py >}}
```

### Model class

A new attribute `doctor_time_used` is used to record the total time patients spend with doctor. This value is reset at the end of any warm-up period, so that only data from the main collection phase is analysed.

Recording the time used requires two corrections:

**End of simulation overrun**. If a consultation begins during the data collection period and extends past the simulation end, only the time up to simulation end is included. This prevents overestimating usage by excluding extra time beyond the simulation window.

**Warm-up overrun**. For models with a warm-up, consultations that begin during warm-up but finish during data collection would be missed after the reset, leading to underestimated usage. To correct for this, any time overlapping data collection (for these patients) is recorded in the `doctor_time_used_correction` attribute and added back in after the warm-up reset.

```{python}
class Model:
    """
    Simulation model.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    run_number : int
        Run number for random seed generation.
    env : simpy.Environment
        The SimPy environment for the simulation.
    doctor : simpy.Resource
        SimPy resource representing doctors.
    patients : list
        List of Patient objects.
    doctor_time_used : float#<<
        Total time that doctor resources were used for (minutes).#<<
    doctor_time_used_correction : float#<<
        Adjustment for doctor time. Without this, usage is underestimated#<<
        since patients whose consultations began in warm-up but ended#<<
        during data collection are excluded.#<<
    results_list : list
        List of dictionaries with the attributes of each patient.
    arrival_dist : Exponential
        Distribution used to generate random patient inter-arrival times.
    consult_dist : Exponential
        Distribution used to generate length of a doctor's consultation.
    """
    def __init__(self, param, run_number):
        """
        Create a new Model instance.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        run_number : int
            Run number for random seed generation.
        """
        self.param = param
        self.run_number = run_number

        # Create SimPy environment
        self.env = simpy.Environment()

        # Create resource
        self.doctor = simpy.Resource(
            self.env, capacity=self.param.number_of_doctors
        )

        # Create a random seed sequence based on the run number
        ss = np.random.SeedSequence(self.run_number)
        seeds = ss.spawn(2)

        # Set up attributes to store results
        self.patients = []
        self.results_list = []
        self.doctor_time_used = 0#<<
        self.doctor_time_used_correction = 0#<<

        # Initialise distributions
        self.arrival_dist = Exponential(mean=self.param.interarrival_time,
                                        random_seed=seeds[0])
        self.consult_dist = Exponential(mean=self.param.consultation_time,
                                        random_seed=seeds[1])

    def generate_arrivals(self):
        """
        Process that generates patient arrivals.
        """
        while True:
            # Sample and pass time to next arrival
            sampled_iat = self.arrival_dist.sample()
            yield self.env.timeout(sampled_iat)

            # Check whether arrived during warm-up or data collection
            if self.env.now < self.param.warm_up_period:
                period = "\U0001F538 WU"
            else:
                period = "\U0001F539 DC"

            # Create a new patient
            patient = Patient(patient_id=len(self.patients)+1,
                              period=period)
            self.patients.append(patient)

            # Print arrival time
            if self.param.verbose:
                print(f"{patient.period} Patient {patient.patient_id} " +
                      f"arrives at time: {self.env.now:.3f}")

            # Start process of consultation
            self.env.process(self.consultation(patient))

    def consultation(self, patient):
        """
        Process that simulates a consultation.

        Parameters
        ----------
        patient :
            Instance of the Patient() class representing a single patient.
        """
        # Patient requests access to a doctor (resource)
        with self.doctor.request() as req:
            yield req

            if self.param.verbose:
                print(f"{patient.period} Patient {patient.patient_id} starts " +
                      f"consultation at: {self.env.now:.3f}")

            # Sample consultation duration
            time_with_doctor = self.consult_dist.sample()

            # Add to total doctor time used#<<
            # If it runs past simulation end, only count the time until end#<<
            remaining_time = (#<<
                self.param.warm_up_period +#<<
                self.param.data_collection_period) - self.env.now#<<
            self.doctor_time_used += min(#<<
                time_with_doctor, remaining_time)#<<

            # During warm-up: check if consultation continues past warm-up.#<<
            # If so, record the portion overlapping with data collection in#<<
            # doctor_time_used_correction (capped at the simulation end).#<<
            remaining_warmup = self.param.warm_up_period - self.env.now#<<
            if remaining_warmup > 0:#<<
                time_exceeding_warmup = time_with_doctor - remaining_warmup#<<
                if time_exceeding_warmup > 0:#<<
                    self.doctor_time_used_correction += min(#<<
                        time_exceeding_warmup,#<<
                        self.param.data_collection_period)#<<

            # Pass time spent with the doctor
            yield self.env.timeout(time_with_doctor)

    def reset_results(self):
        """
        Reset results.
        """
        self.patients = []
        self.doctor_time_used = 0#<<

    def warmup(self):
        """
        Reset result collection after the warm-up period.
        """
        if self.param.warm_up_period > 0:
            # Delay process until warm-up period has completed
            yield self.env.timeout(self.param.warm_up_period)

            # Reset results variables
            self.reset_results()
            if self.param.verbose:
                print(f"Warm up period ended at time: {self.env.now}")

            # Add correction for patients whose consultations began in#<<
            # warm-up but continued into data collection.#<<
            self.doctor_time_used += self.doctor_time_used_correction#<<

    def run(self):
        """
        Run the simulation.
        """
        # Schedule arrival generator and warm-up
        self.env.process(self.generate_arrivals())
        self.env.process(self.warmup())
        # Run the simulation
        self.env.run(until=(self.param.warm_up_period +
                            self.param.data_collection_period))
        # Create list of dictionaries containing each patient's attributes
        self.results_list = [x.__dict__ for x in self.patients]
```

### Runner class

Mean utilisation measures the proportion of available doctor time that is actually used during the data collection period. It is calculated here as:

$$
\text{mean utilisation} = \frac{\text{doctor\_time\_used}}{\text{number of doctors} \times \text{data collection period}}
$$

```{python}
class Runner:
    """
    Run the simulation.

    Attributes
    ----------
    param : Parameters
        Simulation parameters.
    """
    def __init__(self, param):
        """
        Initialise a new instance of the Runner class.

        Parameters
        ----------
        param : Parameters
            Simulation parameters.
        """
        self.param = param

    def run_single(self, run):
        """
        Runs the simulation once and performs results calculations.

        Parameters
        ----------
        run : int
            Run number for the simulation.

        Returns
        -------
        dict
            Contains patient-level results and results from each run.
        """
        model = Model(param=self.param, run_number=run)
        model.run()

        # Patient results
        patient_results = pd.DataFrame(model.results_list)
        patient_results["run"] = run

        # Run results
        run_results = {
            "run_number": run,
            "mean_utilisation": model.doctor_time_used / (#<<
                self.param.number_of_doctors *#<<
                self.param.data_collection_period#<<
            )#<<
        }

        return {
            "patient": patient_results,
            "run": run_results
        }
```

### Run the model

In `result["run"]`, we can see the mean utilisation.

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["run"])
```

:::

In this second approach, the calculation is time-weighted...

::: {.callout title="▶&nbsp;&nbsp;View how to record utilisation (time-weighted approach)" collapse="true"}

:::

::::

::: {.r-content}

::: {.callout title="▶&nbsp;&nbsp;View how to record utilisation (time-weighted approach)" collapse="true"}

::::

::::

## 📏 Mean queue length

> **Corresponding term in queueing theory:** Average number in queue, $L_q$

:::: {.callout title="▶&nbsp;&nbsp;View how to record mean queue length" collapse="true"}

::: {.python-content}

### Parameter class

```{python}
#| echo: false
{{< include outputs_resources/parameters.py >}}
```

### Patient class

```{python}
#| echo: false
{{< include outputs_resources/patient.py >}}
```

### Model class

```{python}
#| echo: false
{{< include outputs_resources/model.py >}}
```

### Runner class

```{python}
#| echo: false
{{< include outputs_resources/runner.py >}}
```

### Run the model

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["run"])
```

:::

::: {.r-content}

:::

::::

## ⏳ Mean time in system

> **Corresponding term in queueing theory:** Average time in system, $\\W$

:::: {.callout title="▶&nbsp;&nbsp;View how to record mean time in system" collapse="true"}

::: {.python-content}

### Parameter class

```{python}
#| echo: false
{{< include outputs_resources/parameters.py >}}
```

### Patient class

```{python}
#| echo: false
{{< include outputs_resources/patient.py >}}
```

### Model class

```{python}
#| echo: false
{{< include outputs_resources/model.py >}}
```

### Runner class

```{python}
#| echo: false
{{< include outputs_resources/runner.py >}}
```

### Run the model

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["run"])
```

:::

::: {.r-content}

:::

::::

## 👥 Mean number of patients in the system

> **Corresponding term in queueing theory:** Mean system size or average number in the system, $L$

:::: {.callout title="▶&nbsp;&nbsp;View how to record mean number of patients in the system" collapse="true"}

::: {.python-content}

### Parameter class

```{python}
#| echo: false
{{< include outputs_resources/parameters.py >}}
```

### Patient class

```{python}
#| echo: false
{{< include outputs_resources/patient.py >}}
```

### Model class

```{python}
#| echo: false
{{< include outputs_resources/model.py >}}
```

### Runner class

```{python}
#| echo: false
{{< include outputs_resources/runner.py >}}
```

### Run the model

```{python}
runner = Runner(param=Parameters())
result = runner.run_single(run=0)
print(result["run"])
```

:::

::: {.r-content}

:::

::::

## 🙈 Unseen (backlogged) patients

Backlogged/unfinished patients (remaining in the system at termination).

<!--TODO: why to measure... what you miss if you don't-->

### Backlogged patient count

:::: {.callout title="▶&nbsp;&nbsp;View how to record the backlogged patient count" collapse="true"}

::::

### Backlogged patient mean wait time

:::: {.callout title="▶&nbsp;&nbsp;View how to record the backlogged patient mean wait time" collapse="true"}

::::

## 📋 Summary of performance measures

| Performance measure | - | - |
| - | - | - |
| Total arrivals |
| Mean wait time |
| Mean time in consultation |
| Mean doctor utilisation |
| Mean queue length |
| Mean time in system |
| Mean number of patients in the system |
| Backlogged patient count |
| Backlogged patient mean wait time |

<!--TODO: table... which include what patients i.e. warmup, not, unseen-->

## 🔍 Explore the example models

<div class="h3-tight"></div>

### 🩺 Nurse visit simulation

:::: {.python-content}

{{< include ../../html/pydesrapmms.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** |  |
| **What to look for?** |  |
| **Why it matters?** |  |
: {tbl-colwidths="[20,80]"}
:::

::::

:::: {.r-content}

{{< include ../../html/rdesrapmms.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** |  |
| **What to look for?** |  |
| **Why it matters?** |  |
: {tbl-colwidths="[20,80]"}
:::

::::

### 🧠 Stroke pathway simulation

:::: {.python-content}

{{< include ../../html/pydesrapstroke.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** |  |
| **What to look for?** |  |
| **Why it matters?** |  |
: {tbl-colwidths="[20,80]"}
:::

::::

:::: {.r-content}

{{< include ../../html/rdesrapstroke.html >}}

::: {.blue-table}
| | |
| - | - |
| **Key file** |  |
| **What to look for?** |  |
| **Why it matters?** |  |
: {tbl-colwidths="[20,80]"}
:::

::::

## 🧪 Test yourself

<br><br>
