name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:

        - name: Check out repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Configure Git safe directory
          run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

        - name: Restore renv dependencies
          run: |
            Rscript -e "renv::restore()"

        - name: Lint
          run: |
            bash lint.sh