name: Check Alt Text

on:
  push:
    paths:
      - '**.qmd'
  pull_request:
    paths:
      - '**.qmd'
  workflow_dispatch:

jobs:
  check-alt-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check images for alt text
        run: python lint_alt_text.py
