name: Update GitHub pages
run-name: Render Quarto website and publish on GitHub pages

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R system dependencies
        uses: sudo apt-get install -y libpng-dev

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Set up Python conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: des-rap-book
          environment-file: environment.yaml
          auto-update-conda: true
          python-version: "3.9"

      - name: Render and publish to GitHub pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}